GET http://localhost/

###

GET https://qlient.net/soov

###

POST http://localhost/users
Content-Type: application/json

{
    "name": "Cringelord",
    "password": "password"
}

###

POST http://localhost/qetroxlol
Content-Type: application/json

{
    "type": "minecraft",
    "redeemed_by": "QetroxLOL",
    "event_type":"creeper_play_sound"
}

###

POST http://localhost/qetroxlol
Content-Type: application/json

{
    "type": "minecraft",
    "data": {
        "redeemed_by": "QetroxLOL",
        "type":"custom",
        "command": "op qetrox"
    }
}

###

POST http://localhost/users/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ3JpbmdlbG9yZCIsImlhdCI6MTY5OTMxMjY1M30.V7Chh8QIPw_-2sEtAO9VBbzhO-29Z8Qi6ni5tF_i5-E"
}

###

GET http://localhost/streamer/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiQ3JpbmdlbG9yZCIsImlhdCI6MTY5OTI4MzEzMywiZXhwIjoxNjk5MjgzMTQ4fQ.SQf3bpD371drIsKiU-FSA0LlE0LtJbftYu-uh1SS2QE